import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Send } from "lucide-react";

const ChatInput = () => {
  const [message, setMessage] = useState("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (message.trim()) {
      // Handle message submission here
      console.log("Sending message:", message);
      setMessage("");
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  return (
    <div className="border-t border-border bg-card px-6 py-4">
      <form onSubmit={handleSubmit} className="flex items-end gap-3 max-w-4xl mx-auto">
        <div className="flex-1">
          <Textarea
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Send a message..."
            className="min-h-[48px] max-h-32 resize-none bg-chat-input-bg border-border focus:ring-iu-red focus:border-iu-red"
            rows={1}
          />
        </div>
        <Button 
          type="submit" 
          size="icon"
          className="h-12 w-12 bg-iu-red hover:bg-iu-red-light"
          disabled={!message.trim()}
        >
          <Send className="h-4 w-4" />
        </Button>
      </form>
      
      <div className="text-center mt-3">
        <p className="text-xs text-text-subtle max-w-4xl mx-auto">
          Please note that responses are generated by an AI language model and may contain errors, inconsistencies, or outdated information. It's advisable to independently verify the responses.{" "}
          <span className="text-iu-red cursor-pointer hover:underline">
            Chat AIU privacy notice
          </span>
        </p>
      </div>
    </div>
  );
};

export default ChatInput;